"""Updated Influencer model with email and platform

Revision ID: 382364038e4e
Revises: a78989348a87
Create Date: 2025-04-09 10:07:20.582786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382364038e4e'
down_revision = 'a78989348a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
