"""Add campaign_goals to Sponsor

Revision ID: cbddf1143615
Revises: 382364038e4e
Create Date: 2025-04-09 10:08:47.689880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbddf1143615'
down_revision = '382364038e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_goals', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_column('campaign_goals')

    # ### end Alembic commands ###
